
<?php /*REMOVE O CACHE O JS*/ $token_cache = $this->layout()->tokenJS?>
<script src="<?php echo $this->basePath("/modulo/trafegus/js/grid-fornecedor.js?n=$token_cache") ?>" type="text/javascript"></script>
<?php
echo $this->headLink()->prependStylesheet($this->basePath('/modulo/trafegus/css/admin-default.css')) //estilo padrão do admin?>


<div class="row" >

    <!-- NÚMERO DE COLS PARA FORMULÁRIO -->
    <div class="col-lg-12 col-md-12">
        <!-- Form Elements -->
        <div class="panel panel-default sgc_border-grid">
            <div style="float: right; margin: 8px">
                <a  onclick="window.history.back();" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-chevron-left fa-1x"></i> <strong>Voltar</strong></a>
            </div>
            <div class="panel-heading"><span class="sgc_color-grid"> Motorista </span> - Cadastro de Motorista</div>
            <br>
            <div  class="sgc-espacamento">
                <div  class="row" >
                 
                    <div class="col-lg-12">
                    
                        <div class="sgc-espacamento">
                            <?php
                            $form = $this->form;
                            $form->setAttribute('action', $this->url('motorista', array('action' => 'edit', 'id' => $motorista->getId())));
                            $form->prepare();
                            echo $this->form()->openTag($form);
                            //echo $this->fieldCollection($form);
                            ?> 
                            <!--dados do fornecedos-->
                            <div class="panel panel-default" style="border: 1px solid #95B8E7;padding-bottom: 10px">
                                <div class="panel-heading sgc-heading"><span class="sgc-font-heading">Cadastro de Motorista </span> </div>
                                <div class="sgc-espacamento">
                                    <div  class="col-lg-3">
                                        <?php echo $this->formLabel($form->get('nome')) ?>
                                        <?php echo $this->formElement($form->get('nome')) ?>
                                    </div>
                                    <div  class="col-lg-3">
                                        <?php echo $this->formLabel($form->get('rg')) ?>
                                        <?php echo $this->formElement($form->get('rg')) ?>
                                    </div>
                                    <div  class="col-lg-6">
                                        <?php echo $this->formLabel($form->get('cpf')) ?>
                                        <?php echo $this->formElement($form->get('cpf')) ?>
                                    </div>
                                    <div  class="col-lg-6">
                                        <?php echo $this->formLabel($form->get('telefone')) ?>
                                        <?php echo $this->formElement($form->get('telefone')) ?>
                                    </div>
                                    <div  class="col-lg-6">
                                        <?php echo $this->formLabel($form->get('veiculo')) ?>
                                        <?php echo $this->formElement($form->get('veiculo')) ?>


                                    </div>
                                    <br>
                                    <?php echo $this->formElement($form->get('submit')) ?>
                                    <!--fim dados fornecedor--> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--</div>-->
<!--</div>-->

