<?php /*REMOVE O CACHE O JS*/ $token_cache = $this->layout()->tokenJS?>
<script src="<?php echo $this->basePath("/modulo/trafegus/js/grid-fornecedor.js?n=$token_cache") ?>"
    type="text/javascript"></script>
<?php

echo $this->headLink()->prependStylesheet($this->basePath('/modulo/trafegus/css/admin-default.css'))  //estilo padrão do admin

?>


<div class="row">

    <div class="col-lg-12 col-md-12">
        <!-- Form Elements -->
        <div class="panel panel-default sgc_border-grid">
            <div style="float: right; margin: 8px">
                <a onclick="window.history.back();" class="btn btn-primary btn-sm"><i
                        class="glyphicon glyphicon-chevron-left fa-1x"></i> <strong>Voltar</strong></a>
            </div>
            <div class="panel-heading"><span class="sgc_color-grid"> Motorista </span> - Cadastro de Motorista</div>
            <br>
            <div class="sgc-espacamento">
                <div class="row">

                    <div class="col-lg-12">
                        <div class="sgc-espacamento">
                            <?php
                            $form = $this->form;
                            $form->setAttribute('action', $this->url('veiculo', array('action' => 'add')));
                    
                            $form->prepare();
                            echo $this->form()->openTag($form);
                      
                            ?>
                            <!--dados do fornecedos-->
                            <div class="panel panel-default" style="border: 1px solid #95B8E7;padding-bottom: 10px">
                                <div class="panel-heading sgc-heading"><span class="sgc-font-heading">Cadastro de
                                        Motorista </span> </div>
                                <div class="sgc-espacamento">

                                
                                <div class="flex-container">
                                        <div class="flex-items">
                                            <div class="col-lg-3">
                                                <?php echo $this->formLabel($form->get('placa')) ?>
                                                <?php echo $this->formElement($form->get('placa')) ?>
                                            </div>
                                        </div>
                                       <div class="flex-items">

                                            <div class="col-lg-3">
                                                <?php echo $this->formLabel($form->get('renavam')) ?>
                                                <?php echo $this->formElement($form->get('renavam')) ?>
                                            </div>

                                        </div>
                                    </div>


                                    <br>
                                    <div class="flex-container">
                                        <div class="flex-items">
                                            <div class="col-lg-3">
                                                <?php echo $this->formLabel($form->get('modelo')) ?>
                                                <?php echo $this->formElement($form->get('modelo')) ?>
                                            </div>
                                        </div>
                                       <div class="flex-items">

                                            <div class="col-lg-3">
                                                <?php echo $this->formLabel($form->get('cor')) ?>
                                                <?php echo $this->formElement($form->get('cor')) ?>
                                            </div>

                                        </div>
                                    </div>
                                    <br>
                                    <br>
                                    <div class="flex-container">
                                        <div class="flex-items">
                                            <div class="col-lg-3">
                                                <?php echo $this->formLabel($form->get('marca')) ?>
                                                <?php echo $this->formElement($form->get('marca')) ?>
                                            </div>
                                        </div>
                                        <div class="flex-items">
                                            <div class="col-lg-3">
                                                <?php echo $this->formLabel($form->get('ano')) ?>
                                                <?php echo $this->formElement($form->get('ano')) ?>
                                            </div>
                                        </div>
                                    </div>
                                    <br>
                                    <br>

                                    <br>
                                    <br>
                                    <?php echo $this->formElement($form->get('submit')) ?>
                                    <!--fim dados fornecedor-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>